source 'https://github.com/CocoaPods/Specs.git'
project './BCWeather.xcodeproj'

platform :ios, '12.0'
use_frameworks!

def reusepods
  pod 'AlamofireObjectMapper'
  pod 'AlamofireImage'
  pod 'Swinject'
  pod 'SwiftLint'
end

target 'BCWeather' do
	reusepods
end

target 'BCWeatherTests' do
    platform :ios, '12.0'
    reusepods
end
